#!/bin/bash

echo "You start with $# positional parameters"

#Loop until all parameters are used up

while [ "$1" != "" ]; do
	echo "Parameter 1 equals $1"
	echo "You now have $# positional parameters"
	#Shift all the parameter down by one
	shift

done
