#!/bin/bash

# loan_calc: script to calculate monthly loan payments

PROGNAME="${0##*/}" # Use parameter expansion to get basename

usage () {
	cat <<- _EOF_
	Usage: $PROGNAME PRINCIPLE INTEREST MONTHS
	Where:

	PRINCIPAL is the amount of the loan.
	INTEREST is the APR as a number (7% = 0.07).
	MONTHS is the length of the loan's term.

	_EOF_
}

if (($# != 3)); then
	usage
	exit 1
fi

principal=$1
interest=$2
months=$3

bc <<- _EOF_
	scale = 10
	i = $interest / 12
	p = $principal
	n = $months
	a = p * ((i * ((i + 1) ^ n)) / (((i + 1) ^ n) - 1))
	print a, "\n"
	_EOF_

